### PR TITLE
Feature/tutorial widget

### PR DESCRIPTION
**Pull request by kfilip94**
This PR introduces the tutorial feature.
[PIVOTAL](https://www.pivotaltracker.com/story/show/167700700) | [INVISION](https://projects.invisionapp.com/d/main#/console/17484384/377382957/preview)

Right now we have three tutorial hints available:
- rarity/richness hint appears next to the last selected radio button in the Biodiversity sidebar,
- legend hint, appears when the user has  at least 2 layers activated,
- legend drag hint, appears when the user has  at least 3 layers activated,

e43z7-5bie6

When at least 3 layers are activated, the tutorial messages can be merged into one:
image

Rarity/richness hint appears only on the LAST selected (clicked) layer, @fannycc let me know what do you think about it. I did it because I think it is more intuitive than appearing on the first highlighted layer on the list (but not necessarily the last that was clicked).
70jd9-15yra

I created 2 new components:
- `Tutorial` - it is a wrapper for an element where we want to attach the hint:
image

- `TutorialModal`, one instance of the React Tooltip that we're adding to the `data-globe-component`

If you want to add the tutorial component to the new element, you have to wrap it into `Tutorial` wrapper, pass a new  `tutorialID` prop, and update the `constants/tutorial.js` file with this ID and info text:
image

You can pass additional props like the position (e.g. `top-left` or `top-right`), and additional logical property `showTutorial`.

If you want to remove the tutorial data from local storage and display it again, go to the `Application` tab in the inspect mode and clear local storage:
image

### CODE REVIEW

**Comment by kfilip94** [comment]
:point_up: ready for review

**Comment by weberjavi** [comment]
☝️ checking

**Comment by aabdaab** [comment]
when it's not biodiversity layer, the hint next to the legend isn't opening on clicking:
image

**Comment by kfilip94** [comment]
:point_up: fixed

**Comment by kfilip94** [comment]
@weberjavi, @aabdaab, @fannycc  thank you for your input, I'm going to merge it :muscle:

**Pull request merged**
