### PR TITLE
Feaure/add legend and view switch

### PR DESCRIPTION
**Pull request by weberjavi**
### Description
In this PR the scene mode selector (the widget to switch between the different views of the National Report Cards) is added.
Also the Priority needed and the Protected areas legend items are added to the scene to inform the user and allow to interact with the opacity.
### Designs
Find the designs on this [inVision prototype](https://projects.invisionapp.com/d/main?origin=v7#/console/17484384/421888340/preview?scrollOffset=4509).

image

### Testing instructions
Visit the a National Report Card and play with it :)
### Feature relevant tickets
[View mode selector](https://half-earth-map.atlassian.net/browse/HE-55)
[Priority and protection layers](https://half-earth-map.atlassian.net/browse/HE-57)

### CODE REVIEW

**Comment by weberjavi** [comment]
:point_up: merging this

**Comment by weberjavi** [comment]
You're late to the party :partying_face:

**Comment by tamaramegan** [comment]
Damn!!

**Comment by weberjavi** [comment]
Don't worry I'm opening another PR as we speak

**Pull request merged**
