### PR TITLE
Feature/signed pledge marker

### PR DESCRIPTION
**Pull request by weberjavi**
Working draft of the signed pledge layer (still yet to confirm if this feature will be triggered onLoad or through post robot events).

### CODE REVIEW

**Comment by weberjavi** [comment]
Hey @kfilip94 this is ready to review.
This is the [Pivotal task](https://www.pivotaltracker.com/story/show/168455247)

What I've done in this PR is to take the query params (`signedPledgeZIP` and `signedPledgeCountry`) provided to the `map-iframe` page and display a point on the coordinates returned from the `getCoordsFromZipAndCountry` with the help of the [Locator](https://developers.arcgis.com/javascript/latest/api-reference/esri-tasks-Locator.html) module.

**Comment by kfilip94** [comment]
Hey @weberjavi, everything looks great :confetti_ball: 
I'm wondering if it is possible to pass wrong location data, e.g. zip code that doesn't exist. In this case the site will crash, but I'm not sure if this can happen, does it make sense?
image

**Comment by weberjavi** [comment]
Hey @kfilip94 not really sure how the field on the form to gather the ZIP codes is gonna be implemented, but probably not a dropdown. So yeah it totally makes sense guard the app to enter an undefined coord.
Thanks

**Comment by weberjavi** [comment]
@kfilip94 handling the error now, check it out ☝️ 
Thanks

**Pull request merged**
