### PR TITLE
feature/HE-81-cartographic-review-updates 

### PR DESCRIPTION
**Pull request by weberjavi**
### Description
This PR is the first step into implementing the [cartographic review report solutions](https://basecamp.com/1756858/projects/13899003/messages/97082598). Designs updates have been used in some cases.
Several bugs/regressions have been fixed during the process. Find below a list of the changes:

- **Cartographic review & redesign** 🗺️ 
  - Added extent graphic to mini-map (top right corner) and removed half earth meter link from it.
  - NRCs view switched from `local` to `global`.
  - Updated mask styles on NRCs to avoid complete isolation of the selected country.
  - Neighbouring countries could now be selected through the `overview` globe view on NRCs, following the same flow as in global view.
  - Preliminary updates of the data layers with the new ramps (most of the biodiversity layers are still missing). Legends, checkboxes and widgets ramps have been updated accordingly.
  - Updated zoom and padding on data and featured scenes.
  - Updated HE logo.

- **Bug fixing** 🐛 
  - (NRCs) Avoid going back to `overview` when selecting a new country through `challenges` chart or `ranking`.
  - When going back from an NRC to global the globe will be center on the previously visited country.
  - Removed unused RAISG layers references.
- **Other**
  - Updated API version to `4.20`
  - Added scene to the store.
  - Removed deprecated routes.
### Testing instructions
Test a user flow from global to national report cards

### CODE REVIEW

**Comment by gretacv** [comment]
The mini map is so sexy, love it. I have found an unexpected behaviour. When in the challenge plot, if I change the filter system and then click on a different bubble, it changes the country but the filter does not persist. (see recording attached)

https://user-images.githubusercontent.com/11423895/128838923-9c7648c2-71e3-4503-8ae3-f067d24181c2.mov

**Comment by weberjavi** [comment]
@gretacv I've created a Jira task to handle this behaviour. Do you mind if I sort it on the next PR?
https://vizzuality.atlassian.net/browse/HE-104

**Comment by gretacv** [comment]
The metadata for land human pressures does not show. The slug `land-human-pressures` is in the metadata service. Check this task for the little research I did: https://vizzuality.atlassian.net/browse/HE-87?atlOrigin=eyJpIjoiNWFmYmZhYWY1YWMzNGZkZjlmMDlkZDEwZTlhYjc2ZDgiLCJwIjoiaiJ9

**Comment by gretacv** [comment]
the download this info option appears in the challenge and ranking views, I have created a task for it: https://vizzuality.atlassian.net/browse/HE-106?atlOrigin=eyJpIjoiODYwOTg0ZTM1YjQyNDRjMjhkZjQwOTI4YzkxMGFjNTkiLCJwIjoiaiJ9

**Review by gretacv — CHANGES_REQUESTED** [review]
Looks great Javi ☺️ 
I have added some tasks for both of us. The only thing that bothers me has to do with the land human pressure metadata, the slug is in the service I don't know why it doesn't appear. From my side, once that is fixed or the problem diagnosed, it looks ready to merge.

**Comment by weberjavi** [comment]
Thanks @gretacv!!, will take a look at it

**Comment by gretacv** [comment]
I diagnosed the problem, the slug was wrong in the metadata service. I had added it with underscores instead of dashes. Sorry Javi.

**Pull request merged**
