### PR TITLE
Fix/add loading loaded flags to sidebar components

### PR DESCRIPTION
**Pull request by kfilip94**
This PR clears content inside Species widget and Conservation Efforts widget when new data is being fetched.
5oxal-xsz3b

### CODE REVIEW

**Comment by aabdaab** [comment]
Let's leave it for Monday. I saw some weird edge cases like an empty conservation widget without any explanation. We should thoroughly test it.

**Comment by kfilip94** [comment]
ready again :point_up:

**Comment by aabdaab** [comment]
checking ☝️

**Comment by aabdaab** [comment]
It's not really related to this PR but since I was checking the widgets on the landscape mode on mobile, could you fix the blur on the species widget?:
image
I think adding `<DummyBlurWorkaround />` as an immediate child of a container should fix this.

**Comment by kfilip94** [comment]
fixed, check this again please because this bug appears only on MacOS

**Pull request merged**
