### PR TITLE
Disable interactions on globe when featured place is selected

### PR DESCRIPTION
**Pull request by aabdaab**
Disable all interactions on the globe when the featured place is selected.
For more explanation look [here](https://www.pivotaltracker.com/story/show/168215369)

### CODE REVIEW

**Comment by kfilip94** [comment]
:point_up: checking

**Comment by kfilip94** [comment]
@aabdaab a few things to tweak:
After click on `Explore this area` interactions with the landscape sidebar are disabled.
Also, we can still interact with the globe by using the location button or zoom in/out widget, should we disable them as well?

There is a bug with an area image on the globe, the icon of the first area is it is still visible during the "tour" (check gif below). It is not a part of this PR, but this bug should be fixed somewhere:
wtwnf-m76fx

**Comment by aabdaab** [comment]
I will check it after the core meeting

**Comment by aabdaab** [comment]
```
Also, we can still interact with the globe by using the location button or zoom in/out widget, should we disable them as well?
```

Hmm, good point. I think we can remove them from the viewport the same as we do in the all featured maps list, wdyt?

**Comment by aabdaab** [comment]
- Fixed the bug with landscape mode not being interactive
- Fixed the bug with an area image on the globe, the icon of the first area is it is still visible during the "tour"

Let me know what you think about not showing the widgets on the right side of the screen; location, zoom, zoom out, full screen?

**Comment by kfilip94** [comment]
@aabdaab  thank you for changes, good job ;)
To me you can hide the navigation widgets, I think there is no point to show them in the "tour mode" if we're going to disable them anyway.

**Comment by aabdaab** [comment]
done ☝️

**Comment by kfilip94** [comment]
@aabdaab thanks!

**Pull request merged**
