### PR TITLE
Feature/carto biodiversity layers

### PR DESCRIPTION
**Pull request by weberjavi**
This PR adds Biodiversity layers to the map.
[Pivotal](https://www.pivotaltracker.com/story/show/166211674)

All layer configs and data has been hard coded to avoid making calls to Carto API.

Kapture 2019-06-04 at 15 31 28

There are some bugs related to radio buttons selection and styles. Describing them in this [pivotal ticket](https://www.pivotaltracker.com/story/show/166441788)

### CODE REVIEW

**Comment by weberjavi** [comment]
@aabdaab , @kfilip94 ready to review ☝️

**Comment by weberjavi** [comment]
Gonna fix the conflicts now :(

**Comment by aabdaab** [comment]
great work!! I haven't checked the code yet but found few issues when clicking around:
1. When a layer is selected, unselecting it should remove the radio's fill color\
2. When a layer is selected and you go back to entry boxes and then open Biodiversity sidebar again, the checked radio items are not persisted

**Comment by simaob** [comment]
Some of these issues have been captured on this story: https://www.pivotaltracker.com/story/show/166441788

**Comment by aabdaab** [comment]
merging this then ☝️

**Pull request merged**
