### PR TITLE
Add arrow icons

### PR DESCRIPTION
**Pull request by aabdaab**
Add arrows to Biodiversity Layers in the sidebar:
iconsSwitch

### CODE REVIEW

**Comment by kfilip94** [comment]
@aabdaab Great job, this switch looks much better with the arrow! :+1:
One thing that could be improved is a position of Info icon, I'd prefer to move this icon to the left side, next to the layer title. This would be more coherent with checkbox styles, what do you think?
(below gif with old and then with new position)
xkoni-ms4yk

**Comment by aabdaab** [comment]
It does look better, true, but I think the idea is that the metadata is about rarity and richness rather than the taxa itself... So, visually it should belong to the toggle switch like it does now.

**Comment by kfilip94** [comment]
So maybe this way? We can ask Fausto or Fanny about that.
Screenshot from 2019-06-12 15 15 42

**Comment by fannycc** [comment]
Hiya!

**Comment by aabdaab** [comment]
Fixed the arrows ☝️

**Pull request merged**
