### PR TITLE
Feature/landscape mode grid interaction

### PR DESCRIPTION
**Pull request by weberjavi**
This PR adds multi grid cell selecting functionality on `landscape view`.
When inside landscape view grid cells inside the viewport extent are highlighted.

Kapture 2019-05-02 at 12 52 58

This is the first iteration of multi grid functionality so feel free to comment on this PR to try to achieve the best `Landscape mode` that we can. This call for review is open not just to `code` people. Designers, researchers, PMs and whosoever has a say is welcome to comment.  

As we are not still being able to have access to final data layers some decisions to ease development has been made: 
-  No authentication has been set so every time the app reloads the credentials should be filled (add your ArcGis online credentials to LastPass to ease this flow).
-  Grid layer (`Birds rarity`) should be activated in order to allow multi grid functionality to work. No grid will be displayed as opacity `100%` has been set as default opacity for this layer on ArcGis online scene.

So.. the steps to test this are:
Run `yarn install` >>> run `yarn start` >>> join `localhost:3000` >>> Authenticate yourself with ArcGis online ( EOWilson org) credentials >>> activate `Birds rarity` layer >>> zoom in.

Kapture 2019-05-02 at 13 02 12

There are some quirks on this version (this are the ones that I've spotted):
-  Viewport extent is calculated with a camera tilt of `0º` so when changing the tilt to `45º` sometimes the highlighted grid cells are outside screen edges :(
Maybe this can be fixed by doing some viewport calculations.
-  When triggering location functionality or when zooming to a high zoom level no grid cell is highlighted. Will fix this issue on another PR to avoid making this one to grow wildly. The idea to fix this is to highlight the grid cell in the centre of the viewport  when in landscape mode no grid cell is completely contained by the viewport extent.

### CODE REVIEW

**Comment by aabdaab** [comment]
This might be a part of the fix you mentioned:
- when we use Location widget it's being zoomed in to a high level and no grid cell is highlighted (that's a bug you mentioned) but also when zooming out highlighting is buggy; sometimes it's working, sometimes it's not (it might be threshold of a landscape view and a high zoom level where it stops working)
- something not related to this PR: can we/should we hide the location pin at some point? now, once we hit the location widget there's no option to stop showing the dot. this might not be necessarily an issue, just something to think about.
- sometimes when we zoom in to a high level we go through the globe:
screencast 2019-05-08 11-44-31

**Comment by weberjavi** [comment]
Hey @aabdaab about your first concern (`buggy highlighting`) might it be related to the issue that the contained grid cells are calculated through camera `extent` and it does not have into account the `tilt` of the camera (that is it is calculated with a tilt of `0º`)? 
You can test this by manually panning the camera `tilt` to check if the grid cells are inside the viewport.
Kapture 2019-05-08 at 13 24 14

**Comment by weberjavi** [comment]
About the `location` widget pin I think we might display anything we want (a geometry, a marker...) or nothing at all:
https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Locate.html#graphic

Maybe something to talk about with the design team.

**Comment by aabdaab** [comment]
Regarding the `buggy highlighting` it indeed may be referenced by this issue:
>Viewport extent is calculated with a camera tilt of 0º so when changing the tilt to 45º sometimes the highlighted grid cells are outside screen edges :(
The two other issues I added as questions to raise with John and Fanny&Fausto so we keep them in mind: https://paper.dropbox.com/doc/Tasks-9th-May-Pkx4l05cJGYRMJOUGLDAX

**Comment by kfilip94** [comment]
@weberjavi I'm struggling with this cell selection feature, probably I'm doing something wrong but for me it is almost impossible to see selected cell after zoom (green rectangle), is it this same bug as `buggy highlighting` mentioned before?

uh4ez-phmqg

**Comment by weberjavi** [comment]
@kfilip94 more than restricting zoom level I think it would be better to enable the selection of the grid cell in the centre of the view port once no grid cell is `contained` anymore.
I've created [this pivotal task to handle that functionality](https://www.pivotaltracker.com/story/show/165964967)

**Comment by weberjavi** [comment]
@aabdaab , @kfilip94 if you think this PR is a good starting point to keep improving landscape view lets move it forward.
We are not having yet the chance to show it to the rest of the team (on the demo server) as it is not yet set up. But we might do it on next iterations.

**Pull request merged**
