### PR TITLE
Chore/api version upgrade 4.12

### PR DESCRIPTION
**Pull request by weberjavi**
This PR upgrades the version of the ArcGIS js API used in the project from 4.11 to 4.12

Some fixes to breaking changes have been made.
- Group layers need to be active in order for their sub layers to display on screen.
- A `returnGeometry`  attribute with value `true` has been added to the `query` object of the `queryFeature` method on the facets layer. That was needed in order to calculate the aggregated grid cell.
- A workaround to a bug related to `imageryLayer`s `mosaic rules` has been added to the `onLoad` function.

### CODE REVIEW

**Comment by weberjavi** [comment]
PS: you should change this `.env` variable:
`REACT_APP_ARGISJS_API_VERSION=4.12`

**Comment by weberjavi** [comment]
@kfilip94 , @aabdaab please do not let this PR with out checking, as we will be referring to updated documentation on  ArcGIS js (https://developers.arcgis.com/javascript/latest/api-reference/) and that docs are from version `4.12` so somethings might not work on version `4.11` and we wouldn't know why.

**Comment by kfilip94** [comment]
It seems to be working fine, I didn't find any new issue. :+1: 
Btw. this new 4.12 version brings a few cool features, I checked the [Release notes for 4.12](https://developers.arcgis.com/javascript/latest/guide/release-notes/), maybe we can use some of these in the future.

**Comment by weberjavi** [comment]
@kfilip94 should I merge it? Is it approved?

**Comment by kfilip94** [comment]
@aabdaab do you want to take a look at this before the merge?

**Comment by aabdaab** [comment]
I'll merge it myself to be able to fully review #47

**Pull request merged**
