### PR TITLE
Feature/global marine encroachment layer

### PR DESCRIPTION
**Pull request by weberjavi**
### Description
This PR adds the marine encroachment section to the Human Pressures global sidebar card. 
From this section checkbox we can now add a new layer to the map (`marine_human_pressures`). The pertinent additions to the project `constants` have been made in order for this to work (`layers-url`, `layers-slugs`, `mol-layers-config`, `layers-groups` and `human-pressures`).
Some small changes have been also made to update the behaviour of the merged human pressures legend item.  
### Designs
[InVision prototype](https://projects.invisionapp.com/d/main?origin=v7#/console/17484384/365562749/preview?scrollOffset=426)
### Testing instructions
Join the [data globe view](http://localhost:3000/dataGlobe) and activate the `marine human modification` layer from the Human pressures sidebar card. Play with the legend interactions (opacity and removing) to test thata all human pressure layers are working accordingly.
### Feature relevant tickets
https://half-earth-map.atlassian.net/browse/HE-165

### CODE REVIEW

**Comment by weberjavi** [comment]
@Bluesmile82 don't forget about this :point_up:

**Comment by Bluesmile82** [comment]
I think is showing the wrong metadata when the info button is pressed

image

**Comment by weberjavi** [comment]
:point_up: metadata added @Bluesmile82

**Review by Bluesmile82 — APPROVED** [review]
Looks great now! Thanks! 🌐

**Pull request merged**
